-- Torii Worker Transaction Queue Table
-- This table stores all transactions from the Torii worker to be executed on Starknet
-- It provides persistence and recovery in case of crashes or restarts

CREATE TABLE IF NOT EXISTS torii_worker_transaction_queue (
  id TEXT PRIMARY KEY,
  contract_address TEXT NOT NULL,
  entrypoint TEXT NOT NULL,
  calldata JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  retries INTEGER NOT NULL DEFAULT 0,
  max_retries INTEGER NOT NULL DEFAULT 3,
  transaction_hash TEXT,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE
);

-- Index for faster queries on status
CREATE INDEX IF NOT EXISTS idx_torii_worker_tx_queue_status ON torii_worker_transaction_queue(status);

-- Index for faster queries on created_at (for ordering)
CREATE INDEX IF NOT EXISTS idx_torii_worker_tx_queue_created_at ON torii_worker_transaction_queue(created_at);

-- Index for combined status + created_at queries (most common query pattern)
CREATE INDEX IF NOT EXISTS idx_torii_worker_tx_queue_status_created_at ON torii_worker_transaction_queue(status, created_at);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update updated_at on every update
DROP TRIGGER IF EXISTS update_torii_worker_tx_queue_updated_at ON torii_worker_transaction_queue;
CREATE TRIGGER update_torii_worker_tx_queue_updated_at
  BEFORE UPDATE ON torii_worker_transaction_queue
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE torii_worker_transaction_queue IS 'Persistent queue for Torii worker Starknet transactions';
COMMENT ON COLUMN torii_worker_transaction_queue.id IS 'Unique transaction ID generated by the worker';
COMMENT ON COLUMN torii_worker_transaction_queue.contract_address IS 'Starknet contract address to call';
COMMENT ON COLUMN torii_worker_transaction_queue.entrypoint IS 'Contract function to execute';
COMMENT ON COLUMN torii_worker_transaction_queue.calldata IS 'Function parameters as JSON array';
COMMENT ON COLUMN torii_worker_transaction_queue.status IS 'Current status: pending, processing, completed, or failed';
COMMENT ON COLUMN torii_worker_transaction_queue.retries IS 'Number of retry attempts made';
COMMENT ON COLUMN torii_worker_transaction_queue.max_retries IS 'Maximum retry attempts allowed';
COMMENT ON COLUMN torii_worker_transaction_queue.transaction_hash IS 'Starknet transaction hash once confirmed';
COMMENT ON COLUMN torii_worker_transaction_queue.error_message IS 'Error message if transaction failed';
COMMENT ON COLUMN torii_worker_transaction_queue.created_at IS 'When the transaction was added to queue';
COMMENT ON COLUMN torii_worker_transaction_queue.updated_at IS 'Last update timestamp';
COMMENT ON COLUMN torii_worker_transaction_queue.completed_at IS 'When the transaction was completed or failed permanently';

-- Enable Row Level Security (RLS)
ALTER TABLE torii_worker_transaction_queue ENABLE ROW LEVEL SECURITY;

-- Create policies to allow all operations with anon key
-- IMPORTANT: This allows full access. In production, you might want more restrictive policies.
CREATE POLICY "Allow all operations on transaction queue"
ON torii_worker_transaction_queue
FOR ALL
USING (true)
WITH CHECK (true);

-- ============================================================================
-- Game Steps Table
-- Stores step-by-step snapshots of game state for replay functionality
-- ============================================================================

CREATE TABLE IF NOT EXISTS game_steps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id INTEGER NOT NULL,
  step INTEGER NOT NULL,
  data JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

  -- Ensure unique combination of game_id and step
  CONSTRAINT unique_game_step UNIQUE (game_id, step)
);

-- Index for faster queries by game_id
CREATE INDEX IF NOT EXISTS idx_game_steps_game_id ON game_steps(game_id);

-- Index for faster queries by game_id and step combination
CREATE INDEX IF NOT EXISTS idx_game_steps_game_id_step ON game_steps(game_id, step);

-- Trigger to update updated_at on every update
DROP TRIGGER IF EXISTS update_game_steps_updated_at ON game_steps;
CREATE TRIGGER update_game_steps_updated_at
  BEFORE UPDATE ON game_steps
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE game_steps IS 'Stores step-by-step snapshots of game state for replay functionality';
COMMENT ON COLUMN game_steps.id IS 'Unique identifier (UUID)';
COMMENT ON COLUMN game_steps.game_id IS 'The ID of the game';
COMMENT ON COLUMN game_steps.step IS 'Step number in the game progression (0-indexed, auto-calculated per game_id)';
COMMENT ON COLUMN game_steps.data IS 'Complete game state data from /api/full-game endpoint';
COMMENT ON COLUMN game_steps.created_at IS 'When the step was recorded';
COMMENT ON COLUMN game_steps.updated_at IS 'Last update timestamp';

-- Enable Row Level Security (RLS)
ALTER TABLE game_steps ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anyone to read all game steps
CREATE POLICY "Allow public read access to game steps"
  ON game_steps
  FOR SELECT
  USING (true);

-- Policy: Allow all operations with anon key (for the worker)
CREATE POLICY "Allow all operations on game steps"
  ON game_steps
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- ============================================================================
-- Leaderboard Reward Periods Table
-- Tracks completed distribution periods to prevent duplicates
-- ============================================================================

CREATE TABLE IF NOT EXISTS leaderboard_reward_periods (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  period_type TEXT NOT NULL CHECK (period_type IN ('daily', 'weekly')),
  period_id TEXT NOT NULL, -- YYYY-MM-DD for daily, YYYY-WNN for weekly
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  total_players INTEGER DEFAULT 0,
  total_packs_distributed INTEGER DEFAULT 0,
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT unique_period UNIQUE (period_type, period_id)
);

-- Index for faster queries on period_type and period_id
CREATE INDEX IF NOT EXISTS idx_leaderboard_reward_periods_type_id ON leaderboard_reward_periods(period_type, period_id);

-- Index for faster queries on status
CREATE INDEX IF NOT EXISTS idx_leaderboard_reward_periods_status ON leaderboard_reward_periods(status);

-- Trigger to update updated_at on every update
DROP TRIGGER IF EXISTS update_leaderboard_reward_periods_updated_at ON leaderboard_reward_periods;
CREATE TRIGGER update_leaderboard_reward_periods_updated_at
  BEFORE UPDATE ON leaderboard_reward_periods
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE leaderboard_reward_periods IS 'Tracks completed leaderboard reward distribution periods to prevent duplicates';
COMMENT ON COLUMN leaderboard_reward_periods.id IS 'Unique identifier (UUID)';
COMMENT ON COLUMN leaderboard_reward_periods.period_type IS 'Type of period: daily or weekly';
COMMENT ON COLUMN leaderboard_reward_periods.period_id IS 'Period identifier: YYYY-MM-DD for daily, YYYY-WNN for weekly';
COMMENT ON COLUMN leaderboard_reward_periods.status IS 'Current status: pending, processing, completed, or failed';
COMMENT ON COLUMN leaderboard_reward_periods.total_players IS 'Number of players who received rewards';
COMMENT ON COLUMN leaderboard_reward_periods.total_packs_distributed IS 'Total number of packs distributed';
COMMENT ON COLUMN leaderboard_reward_periods.started_at IS 'When the distribution started';
COMMENT ON COLUMN leaderboard_reward_periods.completed_at IS 'When the distribution completed or failed';
COMMENT ON COLUMN leaderboard_reward_periods.error_message IS 'Error message if distribution failed';
COMMENT ON COLUMN leaderboard_reward_periods.created_at IS 'When the record was created';
COMMENT ON COLUMN leaderboard_reward_periods.updated_at IS 'Last update timestamp';

-- Enable Row Level Security (RLS)
ALTER TABLE leaderboard_reward_periods ENABLE ROW LEVEL SECURITY;

-- Policy: Allow all operations with anon key (for the worker)
CREATE POLICY "Allow all operations on leaderboard reward periods"
  ON leaderboard_reward_periods
  FOR ALL
  USING (true)
  WITH CHECK (true);

